layout_spectrum: 0.4237379
color:
  saturation: 0.5655209
  brandStrength: 0.7075363
  lightness: 0
  rhythmicContrast: 0.05760031
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.8383458
name: PaleGreenFilm
