typography_spectrum: 0.8383458
color:
  saturation: 0.5655209
  brandStrength: 0.7075363
  lightness: 0
  rhythmicContrast: 0.05760031
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
layout_spectrum: 0.4237379
author:
  name: Chad Tremblay
  email: chad@palegreenstar.com
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a387f66-fa3c-409a-a4ac-6028c4c500d4.png'
name: PaleGreenFilm
title: 'film & photography'
